# Generated by Django 5.1.5 on 2025-01-15 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64)),
                ('annual_income', models.FloatField()),
                ('aadhar_id', models.CharField(max_length=64, unique=True)),
                ('credit_score', models.IntegerField(default=0)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_id', models.CharField(max_length=64)),
                ('registration_date', models.DateTimeField()),
                ('amount', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=8)),
            ],
        ),
    ]
