# Generated by Django 5.1.5 on 2025-01-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInformation',
        ),
    ]
